### ISSUE TITLE
Tracking Issue: Primitive Shapes

### ISSUE THREAD

**Issue by Jondolf** [bevyengine/bevy#10572]
This issue tracks progress on primitive shapes, which were first added in #10466 based on the `primitive-shapes` [RFC](https://github.com/bevyengine/rfcs/blob/main/rfcs/12-primitive-shapes.md).

## Next steps

- [ ] #10569: Support `Mesh` creation from primitive shapes
- [ ] #10570: Add bounding volumes and support computing them for primitive shapes
- [ ] #10571: Support rendering primitive shapes using gizmos
- [ ] Add more primitives
    - Cone
    - Frustum
    - Wedge
    - Torus?
    - Arcs and/or other curves?
- [ ] Add more helper methods to make primitives easier to construct and work with
- [ ] Use for mesh AABBs

## Long-term possibilities

- Bounding Volume Hierarchies (BVH)
    - Broad phase collision detection
    - Spatial query pipeline
    - Rendering
- Frustum culling
- Collider shapes and collision detection for primitives
- Raycasting and other spatial queries for primitives
- Signed Distance Functions (SDF) for primitives

**Comment by rparrett** [comment]
Is this tracking issue still being utilized?

Can we add any of

> Note that some shapes have behavior that can't be exactly reproduced with the new primitives yet:
> - Box is more of an AABB with min/max extents
> - Plane supports a subdivision count
> - Quad has a flipped property (also tracked in #11996)

From #11773 to the list, if still applicable? Plane subdivision, specifically was a hot topic in Discord recently.

**Comment by Jondolf** [comment]
I added the plane subdivision count to the list. The other two aren't as applicable in my opinion; we have AABB types and don't need a `Box` with min/max extents, and the rectangle flipping is perhaps more of a documentation issue than a separate property that we'd need for the mesh.

**Comment by bugsweeper** [comment]
> * Support subdivision for the `Plane3d` mesh

I think `subdivision` param for `Meshable` trait (maybe optional, or maybe in different `MeshableExt` trait) would be rich feature.

**Comment by solis-lumine-vorago** [comment]
I don't understand what is meant by 
> - [ ] Prism

Considering there already is 
> - [ ] support converting 2D shapes to 3D shapes (i.e. extrude circle to get cylinder and so on)

which would basically produce a bunch of prisms. In addition, `Ramp`s already cover (at least some) triangular prisms

**Comment by bugsweeper** [comment]
> * Support subdivisions

Looks like #13719 relates to subdivision

**Comment by bytemunch** [comment]
I've got a naive [ellipsoid implementation](https://github.com/bytemunch/bevy/commit/c27ed0d34c9645df1e74dcdc6339b3c895786ab2) working but it produces meshes identical to a scaled UV sphere, as it uses the sphere UV code with sectors and stacks, substituting variables for `a`, `b`, and `c` where relevant. Is this desirable behaviour or should we strive for a better ellipsoid meshing function?

https://github.com/bevyengine/bevy/assets/43527203/2f3982a4-a974-4b16-bd98-c6957aa36fac
> Scaled spheres in the back, ellipsoids in the front

Also the area calculation uses the [approximate formula](https://en.wikipedia.org/wiki/Ellipsoid#Approximate_formula) which could also be a problem, the maths for integrating everything and getting a closer answer is too much for my brain :exploding_head:

**Comment by rparrett** [comment]
Any plans for an "annular segment" / should that be added to the list?

**Comment by RobWalt** [comment]
> Any plans for an "annular segment" / should that be added to the list?

Sounds good to me. Shouldn't be too diffivult either. I'll glady help with PRs regarding that!

**Comment by tbillington** [comment]
Just chiming in, I've been using the 3d implementations from [Ray Casting for Primitive Shapes#15724](https://github.com/bevyengine/bevy/pull/15724/) in my projects for basic shape raycasting to great success, it would be nice to see something like it in-engine.

**Comment by JasmineLowen** [comment]
> Just chiming in, I've been using the 3d implementations from [Ray Casting for Primitive Shapes#15724](https://github.com/bevyengine/bevy/pull/15724/) in my projects for basic shape raycasting to great success, it would be nice to see something like it in-engine.

I've prioritized this because of you in #24883 💚
