### ISSUE TITLE
Meshlet followup tracking issue

### ISSUE THREAD

**Issue by JMS55** [bevyengine/bevy#11518]
## Short-term memory reduction
- [ ] Instead of writing out 3 u32's per triangle to the index buffer, we can probably get away with just 1
- [ ] Instead of allocating the full index buffer, assume at least some meshlets will be culled and limit the max buffer size

## Important next steps
- [ ] Software raster (avoids the need for writing out an index buffer, and performs better on small triangles) (blocked by https://github.com/gfx-rs/wgpu/issues/5009)
- [ ] Hierarchical LODs

## Miscellaneous optimizations
- [ ] Runtime and disk compression/quantization
  - [ ] Vertex data can be shrunk from 48 packed bytes -> 32 bytes (no packing) by oct-encoding normals, and removing vertex tangents and calculating them in the visbuffer resolve function based on UV derivatives.
- [ ] Test if 128 max vertices per meshlet performs better than 64 on different hardware
- [ ] Single pass compute shader depth pyramid generation (actual shader is extremely fast, but it's a waste to use so many separate passes)
- [ ] Rather than uploading meshlet_previous_thread_ids per meshlet, we can upload an offset per-instance of where to shift the meshlet ids from the current frame to the previous.
- [ ] Consult https://advances.realtimerendering.com/s2021/Karis_Nanite_SIGGRAPH_Advances_2021_final.pdf

## Feature parity
- [ ] Lightmap support
- [ ] Provide asset tools for working with MeshletMeshes in scenes/GLTF files

## Long term
- [ ] Streaming
- [ ] Instead of doing draws per-material, do them per-combination of (pipeline, bind_group). With bindless materials, multiple material instances of the same type should be a single draw.
- [ ] Skinning
- [ ] Material ergonomics (automatically adapt existing shaders by modifying the pipeline descriptor, modifying the shader to fetch vertex data differently, and modifying the shader to replace inbuilt derivatives with derived partial derivatives)
- [ ] Mesh-shader based rendering (wgpu currently lacks support for mesh shaders)
