### ISSUE TITLE
Tracking Issue: Curves Working Group Tasks

### ISSUE THREAD

**Issue by mweatherley** [bevyengine/bevy#13213]
## About

The Curves working group exists to implement the `Curve` API described in [this RFC](https://github.com/bevyengine/rfcs/pull/80) and integrate it into Bevy's existing codebase (primarily in math and animation). 

The design document for this group is [here](https://hackmd.io/@mweatherley/curves-design-doc). 

This working group is coordinated in [this Discord channel](https://discord.com/channels/691052431525675048/1236110755212820581).

If you are interested in contributing to this effort, please check in on Discord first — and, of course, external reviews on related PRs are always welcome. 

## Tasks

- [x] Implement the `Curve` API itself.
    - [x] Implement a viable minimum usable as an interface. (*Blocker for everything.*) (#14630) (#14700).
    - [x] Extend `SampleCurve` and `UnevenSampleCurve` APIs for consumers.
    - [x] Implement `Reflect` on concrete curve types from the API. (*Blocker for `bevy_animation` integration.*)
    - [x] Extend the API to include non-allocating sampling API for curves with dynamically-sized array output. (*Blocker for `bevy_animation` integration.*)
- [x] Integrate the `Curve` API with `bevy_animation`.
    - [x] Replace each component of `VariableCurve` (translation, rotation, scale, morph weights) with a type that implements the associated `Curve` trait. (#15434)
    - [x] Refactor `AnimationTargetContext` to sample from new `VariableCurve` components instead of doing its own interpolation.
    - [x] Benchmark animation update performance and compare the refactored version with the existing one.
- [x] Integrate the `Curve` API with `bevy_math`. 
    - [x] Perform design work on shared API for producing and consuming geometric curves which may be constrained by the input quality (e.g. C0 vs C1 curves).
    - [x] Implement curve-production API for `CubicCurve` and implementors of `CubicGenerator`.
    - [x] Implement curve-production API for `RationalCurve` and implementors of `RationalGenerator`.

## Beyond

This section is for tracking related tasks outside of the scope of the present working group proposal that may be spun off into external issues when this work is completed (or advanced to a sufficient state).

- [x] Investigate the inclusion of more common easing/tweening functions into Bevy itself. 
- [x] Improve the `Reflect` implementations for adaptors in the `Curve` API so that the adaptors are `Reflect` when their bases are.
