### ISSUE TITLE
Mesh2d improvements tracking issues

### ISSUE THREAD

**Issue by IceSentry** [bevyengine/bevy#13265]
## Description

Mesh2d is currently very slow compared to sprites and is also missing quite a few features compared to 3d.

- [ ] Clean up 2d render phases to prepare for adding more phases - https://github.com/bevyengine/bevy/pull/12982
- [ ] Add 2d opaque phase with depth buffer - https://github.com/bevyengine/bevy/pull/13069
- [ ] Enable binning for 2d opaque phase - https://github.com/bevyengine/bevy/pull/13091
- [ ] Add 2d alpha mask phase - No PR yet
- [ ] Investigate using vertex pulling for all mesh2d
- [ ] Switch to using mesh2d as a backend for sprites
- [ ] Investigate if using OIT with binning in 2d can speed up alpha blending compared to sprites.
