### ISSUE TITLE
Comprehensive Source Tracking

### ISSUE THREAD

**Issue by NthTensor** [bevyengine/bevy#16775]
Bevy code can get very spread out. It's not uncommon for very well separated pieces of machinery to have to coordinate, often across crate boundaries. Bevy has great tools to accomplish this sort of coordination, but it is often hard to inspect.

The first attempt at improving runtime inspection was made in https://github.com/bevyengine/bevy/pull/14034, which added optional tracking of exactly where every component is accessed or mutated, as an extension of the change detection system. But there's still several other places we don't track this information.

+ [ ] Add source location tracking to event dispatch, store `Location` in the event queue, and make it possible to iterate events along with source locations.
+ [ ] Add source location tracking to observer triggers, accessible on the `Trigger` object.
+ [ ] Add source location tracking to resource access, though this may happen as part of reunification with components.

**Comment by alice-i-cecile** [comment]
Each of these work items should be tackled one PR at a time to help them get merged in smoothly :)

**Comment by NthTensor** [comment]
Thanks for helping with triage & de-duplication @SpecificProtagonist <3.

**Comment by NthTensor** [comment]
The location would point back to the custom commands though, right? That seems acceptable, it can still help users debug their code.

**Comment by SpecificProtagonist** [comment]
Is there any tracking missing for resources, or can that item be ticked too?

Something else to consider tracking: Component insertions.
