### ISSUE TITLE
Tracking issue for dynamically linked executable size

### ISSUE THREAD

**Issue by bjorn3** [bevyengine/bevy#1911]
This issue tracks reductions in the size of games when compiling in release mode using the `"dynamic"` cargo feature to dynamically link bevy with the fast compile configuration. This is the fastest incremental compilation method for the bevy examples.

# History of `breakout` example size

* [x] https://github.com/bevyengine/bevy/pull/1861: 356k -> 316k (Make some asset loading functions monomorphic)
* [x] https://github.com/bevyengine/bevy/pull/1910: 316k -> 310k (Extract monomorphic get_insert_bundle_info function)
* [x] https://github.com/bevyengine/bevy/pull/1914: 310k -> 293k (Monomorphize various things)

**Comment by bjorn3** [comment]
A lot of space is used for the drop glue of various types.

**Comment by Weibye** [comment]
#1914 Has been merged. Should this issue be considered closed?

**Comment by bjorn3** [comment]
There is no low hanging fruit anymore to improve this I think, so yes.
