### ISSUE TITLE
Tracking issue for common UI widgets

### ISSUE THREAD

**Issue by colepoirier** [bevyengine/bevy#1953]
This issue tracks the common UI widgets (like radio buttons, drop down menus, file pickers) that the UI RFCs should be able to implement.

Using these common widgets as a guide, we can evaluate the completeness and ergonomics of our proposed bevy_ui designs.

This issue can be closed once we're convinced that the RFCs can implement all widgets listed here, then refer back to it during the implementation of the RFCs in many small PRs.

This enables us to start mocking out the solutions to the common widgets and user stories during the design and evaluation of the RFCs and see what we're missing or what's particularly hard.

- [ ] Radio buttons
- [ ] Buttons with text
- [ ] Checkboxes
- [ ] Checklists
- [ ] Sliders
- [ ] Switches (on/off, yes/no, etc.)
- [ ] Drop-down menus
- [ ] File pickers
- [ ] Search bar
- [ ] Text input
- [ ] Complex forms
- [ ] Tabs
- [ ] Side panels
- [ ] Scrollbars
- [ ] Auto-fill text input
- [ ] Auto-complete text input
- [ ] Colour picker
- [ ] Date picker
- [ ] Tooltips
- [ ] Talent trees
- [ ] Building/unit selectors (Age of Empires II like(?))
- [ ] Warcraft 3-style clickable unit abilities
- [ ] Status bars
- [ ] Progress bars
- [ ] Bar graphs
- [ ] Line graphs
- [ ] Pie charts
- [ ] Interactive graphs/charts
- [ ] A Kibana/Graphana style dashboard
- [ ] Hambuger menus
- [ ] Folding named sections of a panel
- [ ] Item picker/selectors
- [ ] Small static table
- [ ] Massive excel-like table

**Comment by skairunner** [comment]
Perhaps tables could be included?

**Comment by colepoirier** [comment]
Some very nice examples of common UI widgets courtesy of @Keavon (https://github.com/Keavon) and his non-destructive vector and raster node editor project Graphite (https://github.com/GraphiteEditor/Graphite)

![keavon_1](https://user-images.githubusercontent.com/37318670/115625381-d8318580-a2b0-11eb-806b-3138eecb8944.png)
![keavon_2](https://user-images.githubusercontent.com/37318670/115625388-db2c7600-a2b0-11eb-9c64-4cda8b9a7e1f.png)
![keavon_3](https://user-images.githubusercontent.com/37318670/115625397-dd8ed000-a2b0-11eb-8c4b-a38469097df2.jpg)

**Comment by Keavon** [comment]
For the record, I would be happy to share the design language between Graphite and Bevy if that, by chance, is within the interests of the team. I was inspired mostly by Blender as well as a number of other common desktop creativity apps for my design of this, with a focus on simplification (simple colors mostly without outlines or shadows, clear use of color, and prioritizing content over distractions from the UI).

**Comment by colepoirier** [comment]
That's very generous of you, thank you @Keavon. It will be up to @cart :) Also sorry for taking 9 months to reply :upside_down_face:

**Comment by alice-i-cecile** [comment]
Closing this out in favor of tracking this in a column on https://github.com/orgs/bevyengine/projects/10 :)

**Comment by TimJentzsch** [comment]
Maybe we should migrate the remaining items in the list to issue drafts in the project

**Comment by alice-i-cecile** [comment]
Agreed. We should try to stick to the simpler primitives however.

Things like talent trees belong in examples at most.
