### ISSUE TITLE
Tracking issue for UI examples

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#1974]
As part of our UI overhaul (#254), we should be sure that we can comfortably produce both common and complex user interfaces. For the most part, these should be mocked out with whatever final solution we pick, and are considered "done" when a pseudocode implementation has been completed and does not have any serious implementation challenges.

This is the current list of UI examples that we're targeting, focusing on diverse and complex examples:

- [ ] To-do list
- [ ] [Oblivion spells UI](https://discord.com/channels/691052431525675048/743663673393938453/834254068741439489)
- [ ] Warcraft 3 building selection
- [ ] Basic editor GUI
- [ ] MOBA controls
- [ ] Mini + full map

If you have other ideas for examples, please comment below with the unique challenges it will provide. We should keep this list reasonably short and diverse to limit the scope of this issue <3

**Comment by RoyAwesome** [comment]
A simple node-graph would be very useful for editor functionality.

**Comment by denormative** [comment]
Probably a pathological case, but "Gold Box UI". :) Most people would think of "RPG Maker" but this goes beyond that towards the dawn of computer games. If I type "san" on the keyboard it selects "Save" from the current menu, then "A" for the save slot, and then "No" I don't want to quit to dos. I don't need to touch the mouse, because there is no mouse. And more importantly I don't need to see.

This probably maps nicely to a controller, but for me it's more an accessibility thing. I've been legally blind for a decade and now I'm getting to the point of being uncorrectably blind. I can focus on the centre of the screen easily enough, but it's more difficult for the random decoration around saying what I need to do, and looking at the controller is even more annoying.

Going back to play these DOS/C64 games I'm enjoying the fact I don't need to see anything but a fraction of the screen, once I've looked at the minimal menu options once and then I can just focus on what is important and type because the menus are 100% keyboard hotkey-ed, and there's only one focus window, and it's reliable.

Like I said, this is probably a pathological edge case, and I'll likely have to program it into my own games as usual, but I suspect a keyboard-only style focused UI might make a lot of other accessibility problems easier as well.

**Comment by Nilirad** [comment]
Charts and data visualization in general could belong there. They are essential for scientific simulation and in general for drawing performance graphs.

**Comment by Nilirad** [comment]
[Radar charts](https://en.wikipedia.org/wiki/Radar_chart) are quite useful in some games, RPGs especially, to visualize multidimensional parameters.

**Comment by Weibye** [comment]
Just came across this resource, which is super useful to this discussion: https://interfaceingame.com/games/

**Comment by Weibye** [comment]
And this, thanks to @aevyrie : https://www.gameuidatabase.com/

**Comment by Weibye** [comment]
We should add the 4-way split screen UI example: 
![image](https://user-images.githubusercontent.com/13300393/182688697-30acdbb1-3c2a-4f18-9a6c-3396d717df12.png)
