### ISSUE TITLE
dead link tracking

### ISSUE THREAD

**Issue by mockersf** [bevyengine/bevy#1983]
Currently dead link check is enabled but doesn't fail in CI due to a lot of dead links. See #1590 

- [ ] `Linked file at path struct.Span.html does not exist!` will be fixed in `tracing` v0.2
- [ ] `into_any*` and `as_any*` comes from an issue in how [`downcast-rs`](https://crates.io/crates/downcast-rs) is built/documented?
- [ ] `sort_by_key` should be solved by rust 1.52

**Comment by mnmaita** [comment]
I assume item number 3 is now resolved, but what about the issue with downcast-rs?
