### ISSUE TITLE
Bevy Development Process

### ISSUE THREAD

**Issue by NathanSWard** [bevyengine/bevy#2256]
[Rendered](https://hackmd.io/@xc_tQrk0TeaEs5PUKUhacg/ryvlM_eKd)

## What problem does this solve or what need does it fill?

A clearer defined set of rules and practices of project management issues for the bevy development process.

Since bevy is exponentially growing and more and more contributors are entering, we need a better defined practice for managing and organizing issues and pull requests.

## What solution would you like?

Introduction of a proper bevy project board inside github, with automated movement between columns based on reviews/approvals etc.
Revamp of github labels.
A `triage-team` or something of the sort for those in change of assigning proper labels.

## What alternative(s) have you considered?

Relying on the current tag/labeling scheme.
- This however is not the best, since there is not a clear/defined structure for adding labels and how to organize the issues/prs that come in.

Using external kanban board software to track issues.
- Relying on external software should be avoided, especially if Github provides the necessary features.

### A few helpful resources
[Github project board automation](https://docs.github.com/en/issues/organizing-your-work-with-project-boards/managing-project-boards/about-automation-for-project-boards)

***TODO***
- [x] Revamp github labels
- [ ] Integrate github project board (and setup automation)
- [x] Add a PR template 
- [x] Automated labeling for PRs (https://github.com/actions/labeler)

**Comment by NathanSWard** [comment]
I'm still a fan of adding the appropriate type emoji on a PR title, if this is something we want to purpose. 
It makes it simple when viewing commits (as the title becomes the first commit line) and being able to tell at a glance what a commit did without reading into it. ☺️☺️

**Comment by alice-i-cecile** [comment]
Can you test what it does to relevant links in a test repo @NathanSWard? That's my largest hesitation left on the gitmoji front.

**Comment by NathanSWard** [comment]
> Can you test what it does to relevant links in a test repo @NathanSWard? That's my largest hesitation left on the gitmoji front.

By relevant links, do you mean when they live in the labels?
Since my current proposal would be to remove them from labels, but add them to the PR titles.

**Comment by alice-i-cecile** [comment]
Oh wait, the PR title isn't part of the PR links. Okay, we're good then.

**Comment by mockersf** [comment]
On the lifecycles, there are no transition to reject / close issues or PRs.

Labels should be prefixed by something indicating their kind: `T-Enhancement`, `C-Audio`, `P-Web`, .... This helps identify them when reading, and also help when adding/editing a pr/issue labels as they will be sorted.

About reviews:
> Once in the Reviewer Approved column, the PR will be officially reviewed by Cart.

I think it's more "the PR will me marked as `S-ready-for-official-review`(or `S-ready-for-cart` while Cart is the only final reviewer, but I would love to move away from naming people in labels). Cart reviews are (currently at least) not direct.

About emojis in PR title: while I like having emojis in the git log, it feels strange having it both in the label and in the PR title. If they differ, what happens?

**Comment by NathanSWard** [comment]
> On the lifecycles, there are no transition to reject / close issues or PRs.

Hm yes this is true. There initially was however since we use `bors`, the original PR is marked as `closed` so there is no way to distinguish between a PR closed by bors and a PR closed because of another reason.
A possible solution to this is adding an `closed` status label which we can put on these PRs?

>Labels should be prefixed by something indicating their kind: T-Enhancement, C-Audio, P-Web, .... This helps identify them when reading, and also help when adding/editing a pr/issue labels as they will be sorted. 

Yep I like this a lot!

> I think it's more "the PR will me marked as S-ready-for-official-review(or S-ready-for-cart while Cart is the only final reviewer, but I would love to move away from naming people in labels). Cart reviews are (currently at least) not direct.

Agreed! I think having a specific label for `ready-for-official-review` would be greatly beneficial and would help organize the PRs.

> About emojis in PR title: while I like having emojis in the git log, it feels strange having it both in the label and in the PR title. If they differ, what happens?

So my solution would be to **only** have the emojis in the PR title and **not** in the label attached to it.

**Comment by mockersf** [comment]
> > On the lifecycles, there are no transition to reject / close issues or PRs.
> 
> Hm yes this is true. There initially was however since we use `bors`, the original PR is marked as `closed` so there is no way to distinguish between a PR closed by bors and a PR closed because of another reason.
> A possible solution to this is adding an `closed` status label which we can put on these PRs?

PRs merged by bors are prefixed with `[Merged by Bors]`, can you catch that?

**Comment by NathanSWard** [comment]
> PRs merged by bors are prefixed with [Merged by Bors], can you catch that?

Not with github automation afaik :(.
However, I just updated the PR labels to include a `S-Closed` for when we close a PR without merging it.

Also, just addresses the other concerns and edited the write up :)

**Comment by NathanSWard** [comment]
@cart 
I would love any additional comments you may have about the current layout :)

**Comment by cart** [comment]
I think we're definitely getting closer now!

>  However, I just updated the PR labels to include a S-Closed for when we close a PR without merging it.

This only works if we remember to add the tag. I want to avoid "extra process" and that definitely feels like it. Additionally, every time someone closes their own pr, now a member of the triage team needs to remember to throw the label on or our entire dataset is compromised. 

> The triage team will [...] as well as updating the PR title to insert content-label.

I dislike this. It is redundant work on top of labels and it isn't easily queryable / structured. Additionally, I think "bug fix" vs "enhancement" is arbitrary enough that it doesn't deserve to be front-and-center in the commit log. Some bug fixes are major enhancements. Some enhancements are also bugfixes. Crude "feature" vs "fix" categories could detract from the messaging / impact of a PR. I think they're still valuable as labels, I just don't think they deserve front-and-center attention.

> emojis in labels / color as category

I'm not a huge fan here either. Compare this bug label from Vue's repo:
![image](https://user-images.githubusercontent.com/2694663/119905804-c2436000-bf01-11eb-858f-992b4356d2cb.png)

To this bug label from Bevy:
![image](https://user-images.githubusercontent.com/2694663/119905838-cff8e580-bf01-11eb-8996-b780aeb57cb3.png)

The image ends up being so small that it stops being legible as a bug. I personally think color is more effective at creating associations. red==bad / bug basically everywhere (yes color perception isn't universal across cultures, but thats also true for emoji perception).

I know this throws a wrench in the "color as category" design. But I think its more useful to use color to assist in distinguishing between "bug" and "enhancement" than it is to distinguish between "bug" and "platform". 

I do think I like the prefixes for category ( [T-], [C-], etc), but I personally think thats enough of a distinguisher. Using color too is redundant information.

> Content [C-]

This feels more like "category" than "content".

> TODO: with the priority label, I’m still not sure if we want to just tag the critical/high priority items, or to have tags for all (e.g. P0, P1, P2, P3).

I'm still very much in favor of only labeling high priority items. "purity" isn't a good enough reason to introduce a bunch of noise into the system imo. Something like 95% of issues will be "normal" priority. And using "critical" / "high" priority gives immediate context relative to, say, P1 and P2 (because users won't know how many priorities there are / what the spectrum is).

**Comment by Weibye** [comment]
Should there be a "Needs RFC" status tag, or is that already covered by "Needs Design"?

**Comment by NathanSWard** [comment]
> This only works if we remember to add the tag. I want to avoid "extra process" and that definitely feels like it.

Yep that's fair. I was mostly looking for a way to distinguish closed/merged PRs, however with bors it makes this a little difficult. So leaving it off is probably best. 

> I dislike this. It is redundant work on top of labels and it isn't easily queryable / structured. Additionally, I think "bug fix" vs "enhancement" is arbitrary enough that it doesn't deserve to be front-and-center in the commit log.

This was referring to the content labels which is (ECS, Assets, Rendering, etc...) 
In do agree that it's extra work and maybe not warranted, but being able to categorize commits by just their first line is very helpful. However I've seen to have gotten quite a but of pushback from both this and the gitmoji, so I'll just ended up removing these for now haha 😅

> The image ends up being so small that it stops being legible as a bug.

Yep I also agree! I actually removed these from the hackmd :wink:

> I do think I like the prefixes for category ( [T-], [C-], etc), but I personally think thats enough of a distinguisher. Using color too is redundant information.

Im definitely on the side of both using the prefix `T-` and colors. The prefix makes it easier to search for a specific label, and also keeps the sorted alphabetically. However I would also argue the colors should stay consistent between label categories, as this helps with visual organization. And it makes chosing a color for a label trivial as you just give it the color of the category it belongs to. Imo, keeping colors consistent doesn't hurt the labels, it can only help in the long run.

> I'm still very much in favor of only labeling high priority items.

I don't feel strongly either way about this, however I do like how only labeling the high priority targets removes a lot of the noise :) 
So I'm happy with only having like `critical` and `high` priority labels :)

**Comment by alice-i-cecile** [comment]
Re: color, I worry that we simply have too many labels to meaningfully use color to describe the content (rather than category) of the label. I suppose we could assign colors to labels at random and then make use of them to distinguish filtered search results?

Using colors for the category helps with labelling, and guides the eye when you're trying to check for the type of information you care about.

> Should there be a "Needs RFC" status tag, or is that already covered by "Needs Design"?

IMO this is covered by "needs design" + "complex".

> This feels more like "category" than "content".

Totally fine by me. I just wanted a different first-letter and "content" was the first word that sprung to mind.

**Comment by cart** [comment]
> A triage-team or something of the sort for those in change of assigning proper labels.
>  Create a triage team?

Haha are you aware that we already have a triage team (and that you are a member)?

**Comment by cart** [comment]
> IMO this is covered by "needs design" + "complex".

agreed. although that might not be immediately apparent to some people. 

> Yep that's fair. I was mostly looking for a way to distinguish closed/merged PRs, however with bors it makes this a little difficult. So leaving it off is probably best.

I really hate that we need to choose between "ideal commit history" and "ideal github states / statistics". Hopefully some saint will find a way to solve this for us: https://github.com/bors-ng/bors-ng/issues/1217

> However I've seen to have gotten quite a but of pushback from both this and the gitmoji, and I'm not longer super in favor of them, so these I'll remove.

Thanks :)

> Using colors for the category helps with labelling, and guides the eye when you're trying to check for the type of information you care about.

Colors are fortunately the easiest thing to change (because we can do it "globally" with a single click). I'm cool with experimenting here. You both like "colors for categories" so I'm cool with try that first (although I do think throwing away red for bugs is a major loss given how common that is / how strong those associations are).

**Comment by alice-i-cecile** [comment]
> although that might not be immediately apparent to some people.

Yeah. That said, I expect that we should basically never be dropping the `needs-rfc` label on others work without any explicit discussion about why (and links to the RFC process for new contributors).

**Comment by cart** [comment]
Good point!

**Comment by NathanSWard** [comment]
As was brought up in #2277 , @alice-i-cecile should we have a content label per crate inside `crates/`?

**Comment by mockersf** [comment]
> As was brought up in #2277 , @alice-i-cecile should we have a content label per crate inside `crates/`?

Not Alice, but I think so!
Would it be possible to add labels automatically based on files changed?

**Comment by alice-i-cecile** [comment]
I'd love this if it was automatic.

**Comment by NathanSWard** [comment]
> Would it be possible to add labels automatically based on files changed?

I'll take a look into this and see if it's possible :)

**Comment by NathanSWard** [comment]
@alice-i-cecile @mockersf 
Looks like this might be able to automate labels depending on which files are edited.
https://github.com/actions/labeler

**Comment by cart** [comment]
I'm not sold on automatic labels yet. Something like a "new cargo fmt rule" would touch everything / add a ton of labels automatically.

I trust people's ability to categorize things more than automation and I think that will produce a better dataset.

**Comment by cart** [comment]
^ forgot to scope this comment specifically to "automatic labels by file path"

**Comment by alice-i-cecile** [comment]
I wonder if we could automatically copy (relevant) labels from linked issues over to the PR 🤔 That's one of the most common patterns, and would improve the starting quality of new PRs a fair bit. Ah well, it's not too bad to do manually.

**Comment by NathanSWard** [comment]
> I trust people's ability to categorize things more than automation and I think that will produce a better dataset.

Yep that's a fair sentiment. It just nice to know that _if_ this is something we eventually want it is possible.

**Comment by NathanSWard** [comment]
Ohh on second thought, since there is no way via GitHub to automatically add labels to PRs (afaik) we could use this to just automatically add the `needs triage` label to any file aka `"*"` 🤔

**Comment by bjorn3** [comment]
> Ohh on second thought, since there is no way via GitHub to automatically add labels to PRs (afaik)

You can use the pull_request_target trigger which runs the master workflow and has a writable github token.

**Comment by NathanSWard** [comment]
Hey all, I would like to finalize the new labeling scheme that is proposed in the referenced HackMD. 

Specifically for the **category** labels I tried to have one per sub-crate in the `crates/` directory (while I grouped a few of them together). 

Please let me know if you have any major concerns with the current proposal so we can iron out the edges here quickly <3

**Comment by cart** [comment]
Yup I think we're in a pretty good spot now. Just a few small things:

* I think the priority category should be red and platform should be green. That lets us utilize the "red gets extra attention" cultural tendency more effectively.
* I think docs and examples are different enough that they merit their own Type
* We should come up with a migration strategy to convert old labels to new labels / preserve existing triage work.

**Comment by mockersf** [comment]
about labels and colors: there are a few that have special meaning in github (top of my head: green/help wanted, purple/good first issue, red/bug) that would be good to keep as standard github

**Comment by cart** [comment]
Agreed. Removing those common colors throws away a lot of useful, already-established context. I also still think using color to distinguish between things _within_ a category is more important than using it to distinguish categories (especially when we already have prefixes for categories). (bug vs enhancement) is way more relevant than (bug vs windows) and there are only 6 categories/types, whereas there are 14 [T] labels and 18 [C] labels.

**Comment by NathanSWard** [comment]
> I think docs and examples are different enough that they merit their own Type

Sounds good, I separated them out into their own labels

> Removing those common colors throws away a lot of useful, already-established context. I also still think using color to distinguish between things within a category is more important than using it to distinguish categories

Sure, I'm not totally against this scheme. 
While I personally would prefer the color coordination within categories, I don't feel super strongly about this, so I'm happy to have specific labels (e.g. `T-bug`) to keep specific colors.
My only question is then for the other labels that we don't have strong opinions about color, e.g. `T-performance` how do we manage that color?
Either 
1) Random
2) Color coordinate each category and then have the select number of outliers stand out with specific colors.
3) Have each category pick a color _pattern_.
e.g. `T-` labels can use warm colors, or more specifically reds/oranges/brown etc... and then platform can use green/cool colors?

My preference is probably #3 (as we have _some_ color coordination, but it's less strict. :smile:

> We should come up with a migration strategy to convert old labels to new labels / preserve existing triage work.

I think the best strategy is: 
1) modify existing labels (that have matching new labels) with the appropriate name and prefix
e.g.
`needs-triage` -> `S-needs-triage`
`meta` -> `C-ecosystem`
`ready-for-cart` -> `S-ready-for-final-reveiw`

2) add new labels that don't exist yet

3) Migrate all labels that we are removing to the new appropriate label
- currently this include:
```
focus-area (removed)
github_actions (combined with `C-ci-build-system`)
question (replaced with `S-needs-investigation`)
rust (collapsed with `T-code-quality` and/or `T-dependencies`)
usability (combined with `T-accessability)
```

4) remove old labels

**Comment by Weibye** [comment]
Should there be category labels for
- AI
- XR
- Modding

?

**Comment by NathanSWard** [comment]
> Should there be category labels for

Added :)

**Comment by alice-i-cecile** [comment]
3 is good color scheme!

Do we have a good "getting to hello world" label? We collect a bunch of those and they'd be nice to deduplicate easily.

**Comment by cart** [comment]
(3) is a good idea, but it still feels like we're throwing out too many color options for each category (there are a ton of labels in each category and we will run out of "warm" colors fast). Maybe we could use "lightness/saturation level" instead? `T-` could be "light / saturated colors", `C-` could be "dark / desaturated colors", `P-` could be fully desaturated (maybe just greyscale ... there aren't that many platforms)

**Comment by Weibye** [comment]
Tried sketching out some examples of (3) while keeping some of github's existing colors. My findings so far is:
* If each category keeps to their own 'theme' and does not have any overlapping colors with other categories, it is going to be challenging also solving for the "distinguish _between_ things within a category"

* I tried assigning some level of importance to some of these labels to see if that could help organize or direct what colors should go where. Downside of this is that there are so many different perspectives: maintainers, traige-team, experienced contributors, new users trying to learn ++. Each group will ascribe their own rules of importance for labels, so unless we dictate a perspective that is de-facto _the_ most important, this isn't particularly useful imo.

* That being said,  have a hunch that the TYPE and STATUS category are the most important categories for every user-group and should stand out from a group of labels. 

* (Github labels-system will ensure readability of these colors)

![image](https://user-images.githubusercontent.com/13300393/121133503-b5dcd280-c832-11eb-8bb3-524e61eb34a8.png)

![image](https://user-images.githubusercontent.com/13300393/121136556-13bee980-c836-11eb-9182-783887dce552.png)

![image](https://user-images.githubusercontent.com/13300393/121133553-c68d4880-c832-11eb-8566-bf0a2e69019b.png)

**Comment by mockersf** [comment]
for colors, I would prefer everything in a category has the same color, except for existing label colors in GitHub universe that would keep their own

**Comment by bjorn3** [comment]
Rust uses O-* for platforms, C-* for the category (bug, enhancement, cleanup, ...), I-* for things like crash, hang, unsoundness and A-* for the area (ecs, sound, ui, ...)

If C-* and I-* are kept in a single category I would prefer the C- prefix over T-. The later is used by rust to mean to which team it applies. Using it in bevy for something else would be slightly confusing IMHO at least to me.

**Comment by cart** [comment]
Yeah I'm down to align with rust here according to the "letter changes"  @bjorn3 laid out.

As far as colors go, I think the scheme @Weibye laid out doesn't have a clear enough distinction between the categories, largely because it tries to re-use colors multiple times within a category (with varying levels of lightness + saturation) and avoids re-using colors across categories. It feels like a "compromise" between "unique colors per category" and "varying lightness per category" that trades off at-a-glace category recognition.

I'll let people propose more color alternatives for about a day, then I'll probably just make a call. No need to block moving forward on picking a palette. We can easily change colors later.

**Comment by Weibye** [comment]
>  I think the scheme @Weibye laid out doesn't have a clear enough distinction between the categories,

I'll try putting up some more color examples in the morning

**Comment by Weibye** [comment]
# Rust-alike labels
This example follow to the most-possible to what is found in the (rust-lang github)[https://github.com/rust-lang/rust/labels?page=1&sort=name-asc]

Notable changes from current Hackmd document:

- `Category` has been redefined to match rust
- `Area` has been introduced to replace previous `Category`
- `Difficulty` has been merged with `Experience`
- `Issue` is a new category with some labels that previously existed under `Type`
- `Platform` gets the prefix `O` instead of `P`

Unresolved questions:
- With this new definition of `Category`, do all the curent entries belong there?
Most of the entries within `Category` are placed under `Teams` in the rust-lang github. The concept of teams does not really apply to us.
Also curious if a label like `S-Invalid` might belong under `Category` instead together with `C-Duplicate`

![image](https://user-images.githubusercontent.com/13300393/121491953-b4e4a600-c9d6-11eb-9bbf-68638f4a2443.png)

# Rust-alike with existing colors
Same as above but keeping existing colors for select labels.

![image](https://user-images.githubusercontent.com/13300393/121492826-80251e80-c9d7-11eb-8b83-7b71fc5599a1.png)


Apologies for the long images, github does not like inline-style in .md documents, also does not seem like I can put them behind spoilers.

**Comment by NathanSWard** [comment]
> This color-scheme follows what is found in the rust-lang github to a reasonable degree.

Wow this looks really good!! :D

The only comment I have I'd I don't think we need the `Issues` labels. 
`I-Needs-Decision` I don't think really provides us with anything.
`I-Crash` shouldn't be limited to issues as someone could open up a PR that fixes some crash in bevy. In which case we'd want the `Crash` label there as well.

**Comment by Weibye** [comment]
> The only comment I have I'd I don't think we need the Issues labels.
I-Needs-Decision I don't think really provides us with anything.
I-Crash shouldn't be limited to issues as someone could open up a PR that fixes some crash in bevy. In which case we'd want the Crash label there as well.

Yeah I completely agree with you. Here, have some more

## Scheme 04: Rust-alike gradients
While it looks _very_ pretty, my primary concern is maintenance. When adding new labels to a category, who would be responsible to pick a new color and how much friction would that entail? (compared to just having fixed colors for the entire group)

Also, lables like `C-Bug` not being red is really not great for readability.

<details>
    <summary>Expand to view</summary> 

  ![image](https://user-images.githubusercontent.com/13300393/121588911-c1005000-ca36-11eb-9dc4-f40cb18c319d.png)

  ![image](https://user-images.githubusercontent.com/13300393/121588981-d6757a00-ca36-11eb-890c-d2f93172f69a.png)


</details>

## Scheme 05: Rust-alike gradients with existing colors

Keeping with the gradients but retaining existing colors. 
Followed @NathanSWard suggestion to scrap the `I-Issue` category and moving them to `C-Category` instead.

When it comes to the existing colors, I would like to suggest _not_ keeping `E-Good-First-Issue`'s existing color, but replacing it with green as seen in scheme 04. 

I really do like that red is a **very exclusive color in this scheme**, which could be put onto other labels we feel strongly about. 
<details>
  <summary>Expand to view</summary>

  ![image](https://user-images.githubusercontent.com/13300393/121592050-84365800-ca3a-11eb-9344-c9afa04f477d.png)

</details>

**Comment by mockersf** [comment]
I prefer 05 without gradient 👍 
* gradient makes it look like some are less important than others, the darker stands out less than the lighter
* gradient will be painful in the future when we want to add a new item to a category and have to check where we stopped, update the gradient, redo all the category if we're getting too close to white/black, ...

**Comment by Weibye** [comment]
### Scheme 06 
This is a non-gradient version of scheme 05. 

This is the colors for each group, with exceptions for the labels that keep their existing color and does not match with the rest of the group.
![image](https://user-images.githubusercontent.com/13300393/121644848-d5266a80-ca93-11eb-83aa-95c2feb2ac40.png)

#### Existing colors
Label | Status
---|---
`C-Bug` | Keeps its color and becomes outlier in group
`C-Crash` | Keeps its color and becomes outlier in group
`C-Invalid` | Keeps its color and becomes outlier in group
`E-Help-Wanted` | Keeps its existing color and the color is adopted to the whole group
`S-Needs-Investigation` | Keeps its existing color and the color is adopted to the whole group
`C-Docs` | Gets new color from the group
`E-Good-First-Issue` | Gets new color from the group
`S-Wontfix` | Gets new color from the group
`C-Duplicate`  | Gets new color from the group

<details>
<summary>Expand to view</summary> 

  ![image](https://user-images.githubusercontent.com/13300393/121644475-53364180-ca93-11eb-95bd-cbfe299bfbac.png)

</details>

Thoughts
- Do `C-Crash` and `C-Bug` need to have different colors or should they simply be the same?
- Is there significant value in keeping `S-Invalid` as an outlier? (I have very little experience with some of these labels)
- Are there other labels that should be outliers, that aren't?

**Comment by Weibye** [comment]
This is what it would look like as labels (using scheme 06)

![image](https://user-images.githubusercontent.com/13300393/121657126-6c91ba80-caa0-11eb-8b37-7dedd01c38d6.png)

**Comment by NathanSWard** [comment]
> Scheme 06

Yep! This looks great! :)
The only thing I would add is that `C-Hotfix` should have its own color (since hotfixes are usually pretty crucial)

**Comment by TheRawMeatball** [comment]
We should probably have a `uses-unsafe` label for PR s

**Comment by Weibye** [comment]
What group / category would `Uses-unsafe` belong under? `Category`?

**Comment by MinerSebas** [comment]
As mentioned in #2436, I think we also need a `Needs Migration Guide` Label.

**Comment by cart** [comment]
I agree (and just created that label ... we can align label naming with the conventions we decide on here)

**Comment by cart** [comment]
Sorry for the delay. Scheme 6 looks reasonable to me. I'm gonna make this the "last call" message so we can move forward.

Leave a :+1: if you agree with adopting Scheme 6
Leave a :-1: if you disagree (and explain why).

I'll give this a few days to collect responses. If we have relative consensus I'll make the switch.

**Comment by mirkoRainer** [comment]
fwiw, as a colorblind user. I appreciate no gradients and text prefix labeling.

**Comment by cart** [comment]
> fwiw, as a colorblind user. I appreciate no gradients and text prefix labeling.

Thanks for calling this out. This was (embarrassingly) not on my radar.

**Comment by NathanSWard** [comment]
Just as a note we'll need to update the PR-labeler action to use the new `triage` label

**Comment by mirkoRainer** [comment]
> > fwiw, as a colorblind user. I appreciate no gradients and text prefix labeling.
> 
> 
> 
> Thanks for calling this out. This was (embarrassingly) not on my radar.

No worries! Luckily most modern OS's have a toggle to make it easier to differentiate colors, but then everything is "off" color. 😵‍💫

Also, the text prefix/tags will help with any high-contrast users as well.

**Comment by cart** [comment]
Alrighty I've done the label migration (including updating our templates and auto labelers)!

#### Changes I made to the current proposal that we can discuss 

* Changed C-Duplicate to S-Duplicate. Imo being a duplicate isn't an "issue category type". It is a status.
* Added a C-Question category (and migrated "question" labels). Whether or not this should exist is up for debate. I think most (if not all) questions should be converted to Github Discussions. As a followup, I think we should do a pass over open issues with this tag, convert the ones that should be discussions, then decide if C-Question is still needed.
* Added C-Usability (and migrated "usability" labels). This seems like a reasonable category and there were many existing issues with the "usability" label.
* Renamed "C-CI-Build-System" to "C-Build-System" because I like the terseness of the latter name and the former is not fun to look at. I think CI fits cleanly into a generic "build system" category.
*  I didn't add the "C-Hotfix" label because we don't have a hotfix process in place yet (ex: we don't yet have a formal process for patch releases). We _should_ come up with a process here and once we do, I'm happy to add the label. But until then its just noise.
* I didn't add a "C-Code-Cleanup" label. I think "C-Code-Quality" encompasses code cleanup.
* I didn't add "A-Ecosystem" and instead renamed "meta" to "A-Meta". "A-Ecosystem" feels more like a "third party dependency" category, which we already have. We use "A-Meta" feels like a good name for what we're using it for: "meta bevy project discussions".
* Didn't add a "S-Invalid" label. The definition was "This is spam, a duplicate issue, or user error". But spam should be deleted, duplicate issues already have the S-Duplicate label, and user error already has the S-User-Error label. If we need more states, we can add them, but S-Invalid felt too generic and overlapped too much. 


#### Next steps 

* Update our project board(s) to account for these new labels
* Convert relevant "C-Question" issues to Github Discussions
* Others should review the current set of labels and make sure everything looks good.

**Comment by mirkoRainer** [comment]
> - Convert relevant "C-Question" issues to Github Discussions

![image](https://user-images.githubusercontent.com/52899592/125542693-6780420f-ef8c-408b-88a2-2aa8c2673e1e.png)

**Comment by cart** [comment]
As a heads up: we opted to roll with automated discussion migration (which maintainers with write access have access to). This preserves comments, reacts, etc.

**Comment by cart** [comment]
I'm going to remove the C-Question label for now. Issues with questions (that don't end up being actionable issues) should be migrated. Just ping me with a link and I'll do it.

Ideally eventually github will give us more control over permissions so I can delegate this work, but currently the only way to delegate is to give other people full write access to the repo, which i don't want to do :smile:

**Comment by cart** [comment]
Just as a heads up, I'm not currently doing the work to set up the project boards. Triage Team members are welcome to collaborate on that.

**Comment by alice-i-cecile** [comment]
> Ideally eventually github will give us more control over permissions so I can delegate this work, but currently the only way to delegate is to give other people full write access to the repo, which i don't want to do 😄

Can @mockersf do this too? Seems to fit well under "uncontroversial cleanup work" .

**Comment by mockersf** [comment]
I don't have write access, I have bors permissions... so I can only do what bors knows how to do.

**Comment by cart** [comment]
Yup because repo write access has the ability to "rewrite history" and there aren't really ways to audit that, I'm pretty hesitant to delegate it even to the most trustworthy of people (and I consider @mockersf pretty trustworthy :smile: ). I'll revisit that if scalability of these types of actions is ever an issue, but for now I really like that bors exclusively exposes "append to history" operations.

**Comment by bjorn3** [comment]
With branch protection I think only admins can rewrite history.

**Comment by cart** [comment]
Ah yeah I think you're right. Even so, the Write role has [way too much control over random things](https://docs.github.com/en/organizations/managing-access-to-your-organizations-repositories/repository-permission-levels-for-an-organization) in the repo: 

I'm still pretty biased to wait until scalability becomes an issue or github gets customizable [RBAC](https://github.com/github/roadmap/issues/111). But knowing that write access can't rewrite protected branches definitely makes me more comfortable.

**Comment by alice-i-cecile** [comment]
I think that `Meta` is actually an Area, not a Content. See this issue, where it's clearly an enhancement to some meta process, or the Contributing.md work, which is a docs improvement to a meta process.

**Comment by cart** [comment]
I'm convinced! Just changed it.

**Comment by TheRawMeatball** [comment]
Hmm, just leaving this so it's not lost: A couple days ago, there was a discussion on [discord](https://discord.com/channels/691052431525675048/692572690833473578/864970400331989032) about what should be issues and what should be discussions.

Personally, I'd prefer to use discussions for feature requests and other nebulous enhancement ideas, while keeping issues for bug reports, tracking issues and immediately actionable stuff, as discussions can do basically everything issues can but better, can be easily converted to issues once they're actionable, and keep the open issue count low (though how important that is can be debated). A counter-point to this is discussions are still in beta, and not a part of most people's github workflows, though this could be fairly easily remedied by noting discussions are prefferred in the enhancements issue template.

**Comment by alice-i-cecile** [comment]
CLosing this out for now.
