### ISSUE TITLE
Tracking issue: deny missing docs, one crate at a time

### ISSUE THREAD

**Issue by alice-i-cecile** [bevyengine/bevy#3492]
Docs are great! However, it's easy to let them atrophy.

As Bevy grows and stabilizes, we want to be able to turn on `#![warn(missing_docs)]` (which will cause CI to fail if violated). This is helpful because it helpful for new users and contributors, and ensures that our code base's documentation state doesn't regress.

However, not everything is stable or well documented enough to do so already.
We should turn this on one crate at a time, once it hits 100% coverage. If there's a crate

Let's check the current doc coverage.

1. Set the following environment variable (on Windows, I used the [`$Env:` syntax](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_environment_variables?view=powershell-7.2)): `RUSTDOCFLAGS="-Z unstable-options --show-coverage"`
2. Run `cargo +nightly doc --workspace --all-features --no-deps` 

Run on 2023-03-14:
**Crate | Docs Coverage** 

- [x] `bevy_a11y` | 100.0%
- [x] `bevy_animation` | 100.0%
- [ ] `bevy_utils` | 53.3%
- [x] `bevy_tasks` | 100.0% (#3509)
- [ ] `bevy_derive` | 33%
- [ ] `bevy_macro_utils` | 28.6%
- [x] `bevy_math` | 100.0% (#3503 | #4591)
- [x] `bevy_app` | 100.0% (#3539)
- [ ] `bevy_ecs_macros` | 40.0%
- [ ] `bevy_dynamic_plugin` | 42.9%
- [ ] `bevy_window` | 97.8% (#4333)
- [x] `bevy_crevice` | **100%** (Not our problem)
- [x] `bevy_log` | 100.0%
- [x] `bevy_transform` | 100.0%
- [x] `bevy_core` | 100.0%
- [ ] `bevy_reflect`| 61.7%
- [ ] `bevy_input` | 90.6% (Claimed by @KDecay)
- [ ] `bevy_gilrs` | 0%
- [ ] `bevy_diagnostic` | 50%
- [ ] `bevy_winit` | 56%
- [x] `bevy_audio` | 100.0%
- [ ] `bevy_scene` | 22.1%
- [x] `bevy_asset` | 100.0% (https://github.com/bevyengine/bevy/pull/3536)
- [ ] `bevy_core_pipeline` | 3.4%
- [ ] `bevy_gltf` |16.7%
- [ ] `bevy_sprite` | 30.8%
- [ ] `bevy_ecs` | 79.5%
- [x] `bevy_dylib` | **100%** (warning not yet enabled) (#3515)
- [ ] `bevy_text` | 35.8%
- [ ] `errors` | 66.7%
- [x] `bevy_internal` | 100.0% (#3514)
- [ ] `bevy_pbr` | 37.4%
- [ ] `bevy_ui` | 74.8%
- [ ] `bevy_render` | 48.2%
- [ ] `bevy_core_pipeline` | 22.3%
- [ ] `bevy_derive` | 57.1%
- [ ] `bevy_encase_derive` | 0%
- [x] `bevy_hierarchy` | 100%
- [x] `bevy_log` | 100%
- [ ] `bevy_mikktspace` | 90%
- [x] `bevy_ptr` | 100%
- [ ] `bevy_reflect_derive`| 88.9%
- [ ] `bevy_render_macros` | 25%
- [ ] `bevy_time` | 78.8%
- [ ] `bevy_utils_macros` | 0%

**Comment by alice-i-cecile** [comment]
So, the steps to tackle this are simple enough.

1. Pick a crate that is small, or nearly documented.
2. Make a PR to finish documenting the crate. If the crate is large, this needs to be split across several PRs to make reviewing easier.
3. Once you've reached 100% coverage, add `#!warn(missing_docs)` to the start of that crate's `lib.rs` file.
4. Repeat 20 or so times.

If you're looking for good candidates, I think the low-hanging fruit here is:
- `bevy_utils`
- `bevy_tasks`
- `bevy_math`
- `bevy_app`
- `bevy_dynamic_plugin`
- `bevy_log`
- `bevy_core`
- `bevy_gilrs`
- `bevy_transform`
- bevy_internal` 

plus the crates that are already at 100% coverage. Feel free to ping me if you would like review or help understanding the code.

**Comment by mfdorst** [comment]
Does it make sense to add that to `bevy_crevice` since it's really on the [`crevice`](https://github.com/LPGhatguy/crevice) maintainers to keep their docs up to date?

**Comment by alice-i-cecile** [comment]
> Does it make sense to add that to bevy_crevice since it's really on the crevice maintainers to keep their docs up to date?

Yeah, I agree with you, since we're basically just mirroring it.

**Comment by KDecay** [comment]
I'm going to document the bevy_math crate and will link the PR here once I'm done.

**Comment by james7132** [comment]
Mentioned this on Discord, but I'll take  on `bevy_tasks`.

**Comment by KDecay** [comment]
I'm going to add the warning to `bevy_dylib` and update the documentation if needed.

**Comment by Sheepyhead** [comment]
I'll be adding the warning to bevy_internal and adding missing docs

**Comment by Sheepyhead** [comment]
I'll be looking at bevy_transform next

**Comment by Sheepyhead** [comment]
I'll take a look at bevy_ui but I make no promises, I think there are parts of this crate I cannot explain yet

**Comment by alice-i-cecile** [comment]
> I'll take a look at bevy_ui but I make no promises, I think there are parts of this crate I cannot explain yet

Sounds good, it's a big crate so even partial progress there will be very helpful.

**Comment by mockersf** [comment]
For the people with ongoing doc PRs (@Sheepyhead, @james7132, @KDecay, @NiklasEi I think?), could you check your PR with the clippy lint `clippy::doc_markdown`?

It should be enabled soon, there was a first pass to fix issues but it's not yet finished, check #3457 for more details. It could be painful to re-introduce issues.

**Comment by KDecay** [comment]
> ... could you check your PR with the clippy lint clippy::doc_markdown?

## bevy_dylib

I just checked this for my PR #3515 that updated the documentation of `bevy_dylib`.
I ran the following command without any errors:

`cargo clippy -p bevy_dylib --no-deps --all-targets --all-features -- -D warnings -A clippy::type_complexity -W clippy::doc_markdown`

## bevy_math / bevy_ui

I also have the PR #3503 that is not completely done yet and updates the documentation of `bevy_math` and parts of `bevy_ui`. I will run the following commands when the PR is ready from my end:

`cargo clippy -p bevy_math --no-deps --all-targets --all-features -- -D warnings -A clippy::type_complexity -W clippy::doc_markdown`

`cargo clippy -p bevy_ui --no-deps --all-targets --all-features -- -D warnings -A clippy::type_complexity -W clippy::doc_markdown`

**Comment by Sheepyhead** [comment]
> could you check your PR with the clippy lint `clippy::doc_markdown`

For the record I find this lint extremely obvoxious, as it assumes anything in a doc with CamelCase is supposed to be backticked

**Comment by james7132** [comment]
Updated my PRs to pass the `docs_markdown` lints.

**Comment by Sheepyhead** [comment]
> Updated my PRs to pass the `docs_markdown` lints.

I have also done this

**Comment by KDecay** [comment]
I'm going to take care of `bevy_input`.

**Comment by NiklasEi** [comment]
@alice-i-cecile could you update the PR description?

**Comment by x-52** [comment]
I'm documenting `bevy_window`. I'll link a PR as soon as I'm done.

**Comment by x-52** [comment]
Uh oh... For some reason, GitHub will close this issue when my PR merges, but we haven't documented all of `bevy` yet!

**Comment by alice-i-cecile** [comment]
> Uh oh... For some reason, GitHub will close this issue when my PR merges, but we haven't documented all of bevy yet!

Doesn't look like it right now; it doesn't show up in the Linked Issues tab. IIRC "Fixes" and "Closes" are both magic words that trigger that. In any case, we can just reopen this if it gets closed by mistake :)

**Comment by x-52** [comment]
Okay, Thanks!

**Comment by adsick** [comment]
there is a missing "unsafe" doc in `DynamicPluginExt`: https://github.com/bevyengine/bevy/blob/520e413c219494b3158ecbdf2b69a786a8469819/crates/bevy_dynamic_plugin/src/loader.rs#LL36C17-L36C17

**Comment by james7132** [comment]
Updating the table we have on the current status of this issue:

|Crate|Doc Coverage|
|:--|:--|
|`bevy_a11y`|100%|
|`bevy_animation`|100%|
|`bevy_app`|100%|
|`bevy_asset`|100%|
|`bevy_audio`|100%|
|`bevy_core_pipeline`|**22.3%**|
|`bevy_core`|100%|
|`bevy_derive`|**57.1%**|
|`bevy_diagnostic`|**50%**|
|`bevy_dylib`|100%|
|`bevy_dynamic_plugin`|**42.9%**|
|`bevy_ecs_macros`|**40%**|
|`bevy_ecs`|**79.5%**|
|`bevy_encase_derive`|**0%**|
|`bevy_gilrs`|**0%**|
|`bevy_gltf`|**16.7%**|
|`bevy_hierarchy`|100%|
|`bevy_input`|**90.6%**|
|`bevy_internal`|100%|
|`bevy_log`|100%|
|`bevy_macro_utils`|**28.6%**|
|`bevy_math`|100%|
|`bevy_mikktspace`|**90%**|
|`bevy_pbr`|**37.4%**|
|`bevy_ptr`|100%|
|`bevy_reflect_derive`|**88.9%**|
|`bevy_reflect`|**61.7%**|
|`bevy_render_macros`|**25%**|
|`bevy_render`|**48.2%**|
|`bevy_scene`|**22.1%**|
|`bevy_sprite`|**30.8%**|
|`bevy_tasks`|100%|
|`bevy_text`|**35.8%**|
|`bevy_time`|**78.8%**|
|`bevy_transform`|100%|
|`bevy_ui`|**74.8%**|
|`bevy_utils_macros`|**0%**|
|`bevy_utils`|100%|
|`bevy_window`|**97.8%**|
|`bevy_winit`|**56%**|

**Comment by targrub** [comment]
Taking the first crate on the list currently missing documentation, `bevy_core_pipeline`, my best judgement (based mostly on those who originally checked in the code in its present location) is that those most familiar with the code, and thus best situated to add the requested documentation, are the following:
@cart --
 `crates/bevy_core_pipeline/src/blit/mod.rs`
 `crates/bevy_core_pipeline/src/clear_color.rs`
 `crates/bevy_core_pipeline/src/core_2d/camera_2d.rs`
 `crates/bevy_core_pipeline/src/core_2d/main_pass_2d_node.rs`
 `crates/bevy_core_pipeline/src/core_2d/mod.rs`
 `crates/bevy_core_pipeline/src/core_3d/camera_3d.rs`
 `crates/bevy_core_pipeline/src/core_3d/main_opaque_pass_3d_node.rs`
 `crates/bevy_core_pipeline/src/core_3d/main_transparent_pass_3d_node.rs`
 `crates/bevy_core_pipeline/src/core_3d/mod.rs`
 `crates/bevy_core_pipeline/src/lib.rs`
 `crates/bevy_core_pipeline/src/msaa_writeback.rs`
@JMS55 --
 `crates/bevy_core_pipeline/src/bloom/mod.rs`
 `crates/bevy_core_pipeline/src/bloom/settings.rs`
 `crates/bevy_core_pipeline/src/taa/mod.rs`
@Elabajaba --
 `crates/bevy_core_pipeline/src/contrast_adaptive_sharpening/mod.rs`
 `crates/bevy_core_pipeline/src/contrast_adaptive_sharpening/node.rs`
@jakobhellermann --
 `crates/bevy_core_pipeline/src/fullscreen_vertex_shader/mod.rs`
 `crates/bevy_core_pipeline/src/tonemapping/mod.rs`
 `crates/bevy_core_pipeline/src/tonemapping/node.rs`
 `crates/bevy_core_pipeline/src/upscaling/mod.rs`
 `crates/bevy_core_pipeline/src/upscaling/node.rs`
@DGriffin91 --
 `crates/bevy_core_pipeline/src/fxaa/mod.rs`
 `crates/bevy_core_pipeline/src/fxaa/node.rs`
@IceSentry --
 `crates/bevy_core_pipeline/src/prepass/mod.rs`
 `crates/bevy_core_pipeline/src/prepass/node.rs`

My apologies if any my guesses were wrong.

**Comment by JMS55** [comment]
My plan is to get to renderer documentation (bevy_render, bevy_core_pipeline, bevy_pbr) sometime soon. I have a couple of open PRs I want to resolve first though.

**Comment by Kanabenki** [comment]
As I started taking a shot a completing the docs for some of the crates, I thought it would be good to have some updated info on the global documentation progress. I only added PR links for those that added the `warn(missing_doc)` attribute once a crate doc was complete. Here's what I got:

- [x] bevy_a11y | 100.0% | (https://github.com/bevyengine/bevy/pull/6874)
- [x] bevy_animation | 100.0% | (https://github.com/bevyengine/bevy/pull/4375)
- [x] bevy_utils | 100.0% (https://github.com/bevyengine/bevy/pull/6897)
- [x] bevy_tasks | 100.0% (https://github.com/bevyengine/bevy/pull/3509)
- [ ] bevy_derive | 57.1%
- [ ] bevy_macro_utils | 35.7%
- [x] bevy_math | 100.0% (https://github.com/bevyengine/bevy/pull/3503 | https://github.com/bevyengine/bevy/pull/4591)
- [x] bevy_app | 100.0% (https://github.com/bevyengine/bevy/pull/3539)
- [ ] bevy_ecs_macros | 36.4%
- [ ] bevy_dynamic_plugin | 42.9%
- [x] bevy_window | 100.0% (https://github.com/bevyengine/bevy/pull/4333) | (https://github.com/bevyengine/bevy/pull/9933)
- [x] bevy_crevice | 100% (Not our problem)
- [x] bevy_log | 100.0% | (https://github.com/bevyengine/bevy/pull/3520)
- [x] bevy_transform | 100.0% | (https://github.com/bevyengine/bevy/pull/3516)
- [x] bevy_core | 100.0% | (https://github.com/bevyengine/bevy/pull/3521)
- [ ] bevy_reflect| 71.1%
- [x] bevy_input | 100.0% | (https://github.com/bevyengine/bevy/pull/9467)
- [ ] bevy_gilrs | 33.3%
- [ ] bevy_diagnostic | 52.2%
- [x] bevy_winit | 100.0% | (https://github.com/bevyengine/bevy/pull/8115)
- [x] bevy_audio | 100.0% | (https://github.com/bevyengine/bevy/pull/3510)
- [ ] bevy_scene | 22.1%
- [ ] bevy_asset | 64.5% | (seems like this one regressed from 100%)
- [ ] bevy_asset_macros | 0.0%
- [ ] bevy_core_pipeline | 26.3%
- [ ] bevy_gltf | 14.9%
- [ ] bevy_sprite | 28.8%
- [ ] bevy_ecs | 100.0% | (https://github.com/bevyengine/bevy/pull/8731)
- [ ] bevy_dylib | 100% (warning not yet enabled) (https://github.com/bevyengine/bevy/pull/3515)
- [ ] bevy_text | 34.9%
- [ ] errors | 66.7%
- [x] bevy_internal | 100.0% (https://github.com/bevyengine/bevy/pull/3514)
- [ ] bevy_pbr | 39.2%
- [ ] bevy_ui | 79.9%
- [ ] bevy_render | 51.2%
- [ ] bevy_core_pipeline | 22.3%
- [ ] bevy_derive | 57.1%
- [ ] bevy_encase_derive | 0%
- [x] bevy_hierarchy | 100% | (https://github.com/bevyengine/bevy/pull/4168)
- [ ] bevy_log | 100%
- [ ] bevy_mikktspace | 90%
- [ ] bevy_ptr | 100% | (https://github.com/bevyengine/bevy/pull/4760)
- [ ] bevy_reflect_derive| 90.9%
- [ ] bevy_render_macros | 25%
- [x] bevy_time | 100.0% | (https://github.com/bevyengine/bevy/pull/9428)
- [ ] bevy_utils_macros | 50.0%
- [ ] bevy_gizmos | 100.0% | (https://github.com/bevyengine/bevy/pull/8186)

**Comment by theotherphil** [comment]
Status after merging https://github.com/bevyengine/bevy/pull/19481.

## Crates with expect(missing_docs)

* bevy_anti_aliasing
* bevy_asset
* ~bevy_asset_macros~
* bevy_core_pipeline
* bevy_encase_derive (external encase derive generates undocumented pub items)
* bevy_image
* bevy_mesh
* ~bevy_mikktspace~
* bevy_pbr
* bevy_render
* bevy_sprite
* bevy_ui
* ~bevy_window~

## Results from --show-coverage

<img width="325" alt="Image" src="https://github.com/user-attachments/assets/c8531175-bb9a-43dd-bcd3-ea9174f020a7" />

Generated from:

```
from IPython.display import display
import json
import os
from pathlib import Path
import polars as pl
import subprocess

# Run rust compiler with --show-coverage to dump stats on doc coverage
def generate_coverage_file(bevy_root: Path, output_file: Path):
    env = os.environ.copy()
    env["RUSTDOCFLAGS"] = "-Z unstable-options --show-coverage --output-format=json"

    with output_file.open(mode="w") as cov:
        subprocess.call(
            "cargo +nightly doc --workspace --all-features --no-deps".split(),
            env=env,
            stdout=cov,
            cwd=bevy_root,
        )

# Rust doc coverage output has one row per crate of the form
# {"crates/bevy_encase_derive/src/lib.rs":{"total":2,"with_docs":0,"total_examples":1,"with_examples":0}}
def read_coverage_dump(cov_dump: Path) -> pl.DataFrame:
    rows = [
         (
            file_name,
            stats["total"],
            stats["with_docs"],
            stats["total_examples"],
            stats["with_examples"],
        )
        for line in cov_dump.read_text().splitlines()
        for file_name, stats in json.loads(line).items()
    ]
    return (
        pl.DataFrame(
            rows,
            schema=["file", "total", "with_docs", "total_examples", "with_examples"],
            orient="row"
        )
        .filter(pl.col("file").str.starts_with("crates/"))
        .with_columns(
            crate=pl.col("file").str.replace_many(["crates/"], "").str.split_exact("/", 1).struct.field("field_0"),
            without_docs=pl.col("total") - pl.col("with_docs")
        )
        .with_columns(
            crate_total_without_docs=pl.col("without_docs").sum().over("crate")
        ).sort("crate_total_without_docs", descending=True)
    )

def display_crate_summary(coverage: pl.DataFrame, ignore_crates: list[str] = []):
    col = "crate_total_without_docs"
    display(
        coverage
        .filter(~pl.col("crate").is_in(ignore_crates))
        .filter(pl.col(col) > 0)
        .group_by("crate")
        .agg(pl.col(col).first())
        .sort(col, descending=True)
    )

pl.Config().set_tbl_rows(30)
pl.Config().set_fmt_str_lengths(100)

bevy_root = Path("<CODE_ROOT>/bevy")
coverage_file = bevy_root / "coverage.json"

generate_coverage_file(bevy_root, coverage_file)
coverage = read_coverage_dump(coverage_file)

display_crate_summary(coverage)
```
