### ISSUE TITLE
Tracking issue: make sure we have Debug implementations for everything

### ISSUE THREAD

**Issue by omarbassam88** [bevyengine/bevy#4089]
This is an issue to track and make sure that we have `Debug` implementations for everything. This can be achieved mostly by just adding `#[derive(Debug)]`. How ever, some custom implementations may be required in some cases. 

Suggestions:
- This should be tracked on a crate-by-crate basis. to help group similar scopes together.
- If the `Debug` implementation is non-trivial, it should be handled in a separate PR, so it's easier to merge.
- As we complete each crate, add `#![warn(missing_debug_implementations)]` to the crate to avoid regressions.

crates:

 - [ ] bevy_app
 - [ ] bevy_asset
 - [ ] bevy_audio
 - [ ] bevy_core
 - [ ] bevy_core_pipeline
 - [ ] bevy_crevice
 - [ ] bevy_derive
 - [ ] bevy_diagnostic
 - [ ] bevy_dylib
 - [ ] bevy_dynamic_plugin
 - [ ] bevy_ecs
 - [ ] bevy_ecs_compile_fail_tests
 - [ ] bevy_gilrs
 - [ ] bevy_gltf
 - [ ] bevy_input
 - [ ] bevy_internal
 - [ ] bevy_log
 - [ ] bevy_macro_utils
 - [ ] bevy_math
 - [ ] bevy_pbr
 - [ ] bevy_reflect
 - [ ] bevy_render
 - [ ] bevy_scene
 - [ ] bevy_sprite
 - [ ] bevy_tasks
 - [ ] bevy_text
 - [ ] bevy_transform
 - [ ] bevy_ui
 - [ ] bevy_utils
 - [ ] bevy_window
 - [ ] bevy_winit

**Comment by bjorn3** [comment]
Adding unused debug implementations increases compilation time, so it may be best to decide for each type if it should be debug and not make private types debug.

**Comment by omarbassam88** [comment]
Just added the PR for the bevy_ecs. 
Here's a list of the files that will need to discuss how to handle the `Debug` Implementation manually:

- [ ] `crates/bevy_ecs/src/system/query.rs`
- [ ] crates/bevy_ecs/src/system/function_system.rs
- [ ] crates/bevy_ecs/src/system/exclusive_system.rs
- [ ] crates/bevy_ecs/src/system/commands/mod.rs
- [ ] crates/bevy_ecs/src/system/commands/command_queue.rs
- [ ] crates/bevy_ecs/src/schedule/mod.rs
- [ ] crates/bevy_ecs/src/schedule/system_set.rs
- [ ] crates/bevy_ecs/src/schedule/system_descriptor.rs
- [ ] crates/bevy_ecs/src/schedule/system_container.rs
- [ ] crates/bevy_ecs/src/schedule/stage.rs
- [ ] crates/bevy_ecs/src/schedule/run_criteria.rs
- [ ] crates/bevy_ecs/src/schedule/executor_parallel.rs
- [ ] crates/bevy_ecs/src/schedule/executor.rs
- [ ] crates/bevy_ecs/src/reflect.rs
- [ ]  crates/bevy_ecs/src/query/state.rs
- [ ] crates/bevy_ecs/src/query/iter.rs
- [ ] crates/bevy_ecs/src/query/filter.rs
- [ ] crates/bevy_ecs/src/query/fetch.rs

**Comment by alice-i-cecile** [comment]
Closing this out <3 As discussed, we shouldn't try and do this systematically.
