### ISSUE TITLE
Tracking issue: dynamic APIs and reflection improvements for scripting

### ISSUE THREAD

**Issue by jakobhellermann** [bevyengine/bevy#4474]
- [ ] #4447 
- [ ] `*const ()` -> `&dyn Reflect` (https://github.com/bevyengine/bevy/pull/4475)
- [ ] by_id component insertion/deletion (currently very tied to rust types and bundles)
- [ ] untyped query (`UntypedQuery::new().read(component_id).write(component_id).without(component_id)` ?)
- [x] struct reflect instead of value for `VecN` (so that `.x` paths work) (https://github.com/bevyengine/bevy/pull/4540)

**Comment by PROMETHIA-27** [comment]
I could try to make a PR to address the reflect type for VecN. Seems like an easy enough change

**Comment by alice-i-cecile** [comment]
Closing in favor of https://github.com/orgs/bevyengine/projects/5 <3
