### ISSUE TITLE
3D Graphics Tracker

### ISSUE THREAD

**Issue by NHodgesVFX** [bevyengine/bevy#4629]
## What problem does this solve or what need does it fill?

I looked through the issues and didn't see any open issues that would give an large overview of needed missing 3D graphics features in Bevy. So, I though I would create this tracker that could remain open and have items ticked of as they are added. Some features have multiple implementations that are possible, although it would be nice to have them all, I think it would be good to start with the easiest to implement in most cases. I am also sure I am forgetting some needed features as well, feel free to add them in the comments or if you have permission add them directly to this post. If this type of issue isnt wanted please feel free to close it :)

## What solution would you like?
**Reflections**

- [ ] Screen Space Reflections (SSR)
- [ ] Planar Reflections
- [ ] (HDRI) Environment Reflections, See #4581
- [ ] Reflection Probes
- [ ] Raytraced Reflections

**Materials**

- [ ] Support Refraction
- [ ] Support [KHR_materials_volume](https://github.com/KhronosGroup/glTF/blob/master/extensions/2.0/Khronos/KHR_materials_volume/README.md)
- [ ] Support KHR_materials_transmission
- [ ] Support [KHR_materials_ior](https://github.com/KhronosGroup/glTF/tree/master/extensions/2.0/Khronos/KHR_materials_ior)
- [ ] SubSurface Scattering (SSS)
- [ ] Alpha to Coverage

**Import**

- [ ] Auto Mip Map Generation
- [ ] Auto UV Generation
- [ ] Auto Normal Generation
- [ ] Auto Tangent Generation
- [ ] Acsii Embedded GTLF Support

**Occlusion**

- [ ] Screen Space Ambient Occlusion (SSAO) 
- [ ] Ground Truth Ambient Occlusion (GTAO)
- [ ] RayTraced Ambient Occlusion (RTAO)
- [ ] Bent Normals 

**Global Illumination**

- [ ] Screen Space Global Illumination (SSGI)
- [ ] Voxel Global Illumination (VXGI)
- [ ] SDF Global Illumination (SDFGI)
- [ ] Lightmaps
- [ ] Directional Lightmaps
- [ ] Light Probes
- [ ] RayTraced Global Illumination (RTGI)

**Lights**

- [ ] Spot Lights 
- [ ] Rect Area Light
- [ ] Tube or Cylindrical Area Light
- [ ] Image Based Lighting, See #4581

**Shadows**

- [ ] Cascaded Shadow Mapping 
- [ ] Percentage Closer Filtering (PCF) 
- [ ] Percentage Closer Soft Shadows (PCSS)
- [ ] RayTraced Shadows

**Effects**

- [ ] Fast approximate anti-aliasing (FXAA)
- [ ] Subpixel Morphological Antialiasing (SMAA)
- [ ] Temporal Anti-Aliasing (TAA)
- [ ] Bloom
- [ ] Tone Mapping
- [ ] Depth Of Field
- [ ] Color Correction
- [ ] Color Grading
- [ ] Volumetric Lighting
- [ ] Depth Fog

**Optimizations**

- [ ] Occlusion Culling

## Additional context

**Refraction**

- https://www.khronos.org/news/press/new-gltf-extensions-raise-the-bar-on-3d-asset-visual-realism

**Comment by alice-i-cecile** [comment]
This is an *excellent* list. I'll defer to @superdump, our rendering lead, for the best format for this.

You may also be interested in the [rendering project board](https://github.com/orgs/bevyengine/projects/3), which is a more operational view of the work that's being done.

**Comment by NHodgesVFX** [comment]
Thanks for the board its really interesting, I had found some of those issues just by searching but their are quite a few I didn't see before.

**Comment by alice-i-cecile** [comment]
If you have the expertise @NHodgesVFX, PR reviews from the community are incredibly valuable to help contributors learn and enable us to merge in features faster. This is especially true in rendering, where the team's expertise can often run a bit thin.

**Comment by NHodgesVFX** [comment]
Thanks, However I don't really have the expertise, I'm pretty new to rust and graphics programming. But maybe I will sometime in the future :)

**Comment by james7132** [comment]
We're already skinning on the GPU.  Unless the suggestion is to use bindless rendering to skin meshes, we're already doing this.

Animation blending and morph target work is already being tracked by #4026.

**Comment by NHodgesVFX** [comment]
I updated the list to reflect that

**Comment by cart** [comment]
Great list! I do think this feels more like Github Discussion territory rather than formal tracking issue territory. "3D graphics features" is a nebulous, large, and ever-changing area that we will never really be able to drive down to zero and close out. Any objections to me converting this to a discussion? You can still use this to track progress, but issues should be "scoped, well defined, and with clear paths to resolution".

**Comment by alice-i-cecile** [comment]
Yeah, I like this as a discussion too :)
