### ISSUE TITLE
Mesh API overhaul (#599 Followup)

### ISSUE THREAD

**Issue by julhe** [bevyengine/bevy#756]
So #599 got merged, but there's more to it:

- [ ] Add API to customize attribute data befor passing to buffer to allow:
         Float -> Half/NormU16/... conversion
         Attribute Packing (is that even still a thing?)
         normal compression
         (custom initialization of undefinied attributes ?)
- [ ]  Allow for multiple attribute buffers.
- [ ]  Replace buffer names with hashes for tighter structs?
- [x]  Allow for VertexAttributeValues to be unloaded after beeing send to GPU to save CPU memory. #1782
- [x]  ~~Allocated one big fallback buffer instead of speperate ones for each mesh.~~ #870
- [x]  Provide example. (see #757)
- [ ]  Quick accsess to common attributes, eg. `Mesh::set_positions(positions: Vec<[f32; 3]>)`?

**Comment by bonsairobo** [comment]
> Allow for VertexAttributeValues to be unloaded after beeing send to GPU to save CPU memory.

Big +1. I have lots of terrain meshes that are hogging a good amount of RAM.

**Comment by ItsDoot** [comment]
The remaining unchecked items have been fulfilled or have equivalents in bevy today (as of `0.14`),
