### ISSUE TITLE
SSAO followup tracking issue

### ISSUE THREAD

**Issue by JMS55** [bevyengine/bevy#8888]
SSAO got merged in #7402, but there's still a lot we can do better.

## Performance
- [ ] Faster depth->world position (see reverted code)
- [ ] Render at half resolution and use a bilateral upsample
- [ ] F16 math (missing naga-wgsl support https://github.com/gfx-rs/naga/issues/1884) 
- [ ] Faster depth mipchain creation (https://github.com/GPUOpen-Effects/FidelityFX-SPD) (wgpu/naga does not currently support subgroup ops)

## Quality
- [ ] Replace the spatial denoiser with a combined spatial+temporal denoiser, similar to bevy_solari's
- [ ] Try interleaved gradient noise or tellusim's spatiotemporal blue noise for sampling
- [ ] Bent normals 
- [ ] Better multibounce approximation (https://drive.google.com/file/d/1SyagcEVplIm2KkRD3WQYSO9O0Iyi1hfy/view)
- [ ] Configurable parameters/heuristics

## Platform Support
- [ ] SSAO currently does not work on DirectX12 due to issues with wgpu and naga:
  * https://github.com/gfx-rs/wgpu/pull/3798
  * https://github.com/gfx-rs/naga/pull/2353 (we have a work-around for this issue in the SSAO shaders atm)
- [ ] SSAO currently does not work on WebGPU because r16float is not a valid storage texture format https://gpuweb.github.io/gpuweb/wgsl/#storage-texel-formats. We can fix this with a fallback to r32float.

## Recent Algorithm Advancements
- [ ] Visibility bitmask (https://link.springer.com/article/10.1007/s00371-022-02703-y, https://cdrinmatane.github.io/posts/cgspotlight-slides/)
- [ ] Screen space diffuse lighting (https://github.com/Patapom/GodComplex/blob/master/Tests/TestHBIL/2018%20Mayaux%20-%20Horizon-Based%20Indirect%20Lighting%20(HBIL).pdf)

**Comment by Elabajaba** [comment]
The `wgpu` backport was released, so SSAO works on DX12 now!

We can get rid of the manual bitmask packing/unpacking implementations in the next wgpu release, as it should have the naga PR included.

**Comment by JMS55** [comment]
Open source reference we can use for visibility bitmasks: https://github.com/4lex4nder/ReshadeEffectShaderToggler-BG3/blob/main/Shaders/bg3_xegtao_gi.fx

**Comment by Anehta** [comment]
WebGPU still cannot run SSAO normally. Is there any other way to support it?

**Comment by JMS55** [comment]
I believe it could be supported now due to `texture-formats-tier1` https://github.com/gpuweb/gpuweb/pull/5160. Don't think wgpu/naga supports it yet, though.

**Comment by janhohenheim** [comment]
Note that WebGPU would still be broken in case a skybox exists: https://github.com/bevyengine/bevy/issues/20459
