### ISSUE TITLE
Tracking issue: Amazing Gizmos

### ISSUE THREAD

**Issue by nicopap** [bevyengine/bevy#9400]
This issue tracks the progress on Gizmo features

### Contributing

Want to check off one of those checkboxes? Nothing easier!

1. [Open a feature request][open-feature-request] you can copy/paste the description if you feel lazy!
2. Implement the feature and open a PR!

All related issues will be listed in this tracking issue.

Not sorted in any specific order:

* [X] **Gizmos MVP** #6529 Make it possible to draw lines on screen, for them to be immediately despawned next frame
* [X] **AABB gizmos** #8468 Draw entity bounding boxes
* [ ] **More than one gizmo kind**: Gizmo line width/depth bias/render layer should be configurable at call site, not just in a resource
  * [ ] **multiple line width**
  * [ ] **multiple depth bias**
  * [ ] **multiple render layers**
* [ ] **Retained gizmos**: We want to give shape to invisible things such as physics collider. It would make more sense to have a retained API for this. Would supersede wireframe rendering #9178
* [ ] **More gizmo shapes**
  * [ ] **arrows**
  * [ ] **grids**
  * [ ] **splines**
  * [ ] **camera**
  * [ ] **mesh wireframe**
  * [ ] **axes**
  * [ ] **light bulb**
* [ ] **Gizmo registry**: Allows plugin to register categories of gizmos and defer to user ability to toggle or control properties of gizmos within a category. See #9187
  * [ ] **System-level gizmo registration**: Automate the gizmo registration by inheriting a system-level registry assignation
* [ ] **Actually-immediate-mode API**: no `SystemParam` required, just a macro/function call to draw gizmos, nothing more. No more need to modify the system signature to add gizmos, or even pass around the gizmo struct, in the style of <https://github.com/nicopap/bevy-debug-text-overlay/>)
* [ ] **dotted lines**: Gizmo with a dotted line effect.
* [ ] **Line caps**: Gizmo squares have ugly corners because the line caps are not filled.
  * [ ] **Square caps**: Extend the gizmo lines by the line width
  * [ ] **Round caps**: Add a semi-circle of line-width radius to the end of lines
  * [ ] **broken caps**: Add a triangle between subsequent gizmo lines
* [ ] **Text gizmos**: Draw text on screen without the `bevy_text` sanctimonious rituals. Just a `gizmo_print!("foobar")` and it would show on screen.
  * [ ] **multiline text**: Should support line returns
  * [ ] **user-provided font**
  * [ ] **Text in 2d space**: Gizmo should let print text on screen on arbitrary positions in 2D games.
  * [ ] **log-style text**:  Users would not provide a position, but it would show up on screen as event in a way similar to a console message in Garry's Mod or Minecraft. Note: This is already implemented as a 3rd party plugin in <https://github.com/nicopap/bevy-debug-text-overlay/>
  * [ ] **Text in 3d space**: Gizmo should let print text in 3D games, may chose to keep the same size with distance or apply perspective.
  * [ ] **Non-overlapping text**: There could be a toggle that allows text placed on screen through 2D or 3D API to not overlap, even if they should, given their provided position.
* [ ] **Filled shape gizmos**: We want to be able to draw filled shapes, this might be useful for special signaling or highlighting areas
  * [ ] **semitransparent filled shape gizmos**: Semi-transparent this becomes apparently much more useful.

**Comment by brandon-reinhart** [comment]
I'm now using gizmos extensively for debug visualizations.

Here's a +1 for filled shapes. One of my gizmos is visualizing a quadtree, another is the nav mesh (using the quadtree) and filled gizmos would let me make an Unreal-style navigable area preview. It works now, just not as easy to look at as it could be.

**Comment by dmyyy** [comment]
https://github.com/bevyengine/bevy/issues/9475 also seems relevant.

**Comment by musjj** [comment]
Could you also add regular and irregular polygons to the list of shapes?

**Comment by nicopap** [comment]
> Could you also add regular and irregular polygons to the list of shapes?

I think it could be better expressed as "2D meshes". I'll reword the post to be more inclusive.

**Comment by SIGSTACKFAULT** [comment]
>  Text in 3d space: Gizmo should let print text in 3D games, may chose to keep the same size with distance or apply perspective.

Should have the choice between the text being billboarded or facing a specific direction

**Comment by SIGSTACKFAULT** [comment]
Could write a polyhedron function with a similar interface to [OpenSCAD's polyhedron() function](https://en.wikibooks.org/wiki/OpenSCAD_User_Manual/Primitive_Solids#polyhedron). And by being less strict about the faces argument it would work for polygons too.

**Comment by SIGSTACKFAULT** [comment]
Under arrows, could you add "double-ended"? thought of it just now

**Comment by nicopap** [comment]
I think passing a `Mesh` to the gizmos would be enough for the polyhedron API (it's listed in the issue as "3D Mesh")

> Under arrows, could you add "double-ended"? thought of it just now but i'll forget by the time i can do it

> Should have the choice between the text being billboarded or facing a specific direction

Added them!

**Comment by Jondolf** [comment]
#11072 technically addressed support for tons of new shapes:

- Ellipse
- Capsule
- Plane (axes and surface normal in 3D)
- Triangle
- Regular polygon
- Cylinder
- Cone
- Conical frustum
- Torus

**Comment by musjj** [comment]
Just asking, but does "Round joints" mean that you can have round corners for the gizmos? Would love to be able to draw rectangles, polygons, etc. with rounded corners.

**Comment by nicopap** [comment]
> does "Round joints" mean that you can have round corners for the gizmos?

Not exactly. Try drawing a rectangle with the current gizmos and a large line width. You'll notice the corners are "cut". The joints would fill the corners. There are several ways to fill the corners, one of them is to fill it with a rounded shape, which we call "rounded joint".

![_Ascreencap](https://github.com/bevyengine/bevy/assets/26321040/9f6a66ec-b12f-4ac0-bc65-a90ebfe946e2)

**Comment by musjj** [comment]
Ah alright, thanks for the explanation. Should I make a new issue about this, or could this just be added to the list above?

**Comment by nicopap** [comment]
Well, there is "Rounded cuboid" but not "rounded arbitrary shapes" which seems to be a bit harder to implement. Though no reasons to add them to the wish list: added!

**Comment by pablo-lua** [comment]
I think we have to support a better way of using multiple windows with gizmos without having to create multiple configs for all windows

**Comment by pablo-lua** [comment]
If there is no problem, I would like to know for sure
the light bulb thing is something like this?
![image](https://github.com/bevyengine/bevy/assets/126117294/86de35ee-1633-4843-86e7-77ffc49d2ebe)

**Comment by pablo-lua** [comment]
Can you mark grid as resolved and add a sub-section "cubic grid"?

**Comment by solis-lumine-vorago** [comment]
Can you mark 3d grid, dotted lines and line joints as resolved please?

**Comment by simbleau** [comment]
Text gizmos... please

**Comment by SIGSTACKFAULT** [comment]
@nicopap double-ended can be ticked off

**Comment by rlidwka** [comment]
For my project, I need text gizmos combined with line gizmos, for example:
 - a straight line, which is interrupted by a text in the middle (with text as a number indicating distance)
 - coordinate axes gizmo with labeled coordinates (with text indicating axis, e.g. x, y, z)

Is there any progress on text gizmos? Or some other way I can achieve this?

**Comment by newclarityex** [comment]
Is z index support planned?
